### ISSUE TITLE
Require public object to setMaxVideoCaptureDuration

### ISSUE THREAD

**Issue by iOSCuriosity** [hackiftekhar/IQMediaPickerController#11]
ENHANCEMENT..!!!! Feature request..!!!!

Currently, I'm using this control in my upcoming app. In which I've to set predefined maxVideoCaptureDuration. But unfortunately, this lib does not include this feature.

I go through the code and found that it can be set in your existing code, but the method is private and i'm using cocoapods.

please update your library and provide this feature asap.

**Comment by hackiftekhar** [comment]
Could you please refresh my memory where can I found maxVideoCaptureDuration property or something like that property in my code?

**Comment by iOSCuriosity** [comment]
I think you got it wrong. I asked you to add feature like "maxVideoCaptureDuration" and set it to public. so one can set "maxVideoCaptureDuration" before capturing video. This is already available in UIImagePickerController.
Also, you may set media size limit in picking up media.

**Comment by hackiftekhar** [comment]
ohh, ok. So you like something like 'maxVideoCaptureDuration'. Great Idea, will do when I get sometime.

**Comment by GABHISEKBUNTY** [comment]
@hackiftekhar  How to get the original image name from the array of retrieved data in swift?
