### ISSUE TITLE
Usage with Swift 3 and Xcode 8

### ISSUE THREAD

**Issue by Mamtak1811** [hackiftekhar/IQMediaPickerController#22]
I'm trying to use this library in swift 3. I have installed the pod, then written `import IQMediaPickerController` in necessary class. Delegate also given beside class name as `, IQMediaPickerControllerDelegate`

The problem is when I create a variable like `var mediapicker = IQMediaPickerController()` and then try to set `mediapicker.delegate = self` , then i get error saying 

>Cannot assign value of type 'CreateAnEventsViewController' to type '(IQMediaPickerControllerDelegate & UINavigationControllerDelegate)?' on `mediapicker.delegate = self` this line.

How do I go about this?
Without delegate being set, i'm able to present the media picker. But i need delegate method calls too.

**Comment by hackiftekhar** [comment]
You have to adopt IQMediaPickerControllerDelegate and UINavigationControllerDelegate protocol on CreateAnEventsViewController
