### ISSUE TITLE
Validate button not showing when allowsPickingMultipleItems = YES

### ISSUE THREAD

**Issue by syc-pad** [hackiftekhar/IQMediaPickerController#24]
Hello @hackiftekhar ,

Thank you for this great library. But I'm facing an issue when I set allowsPickingMultipleItems to YES : the validate button (on top right of the screen) never appears... so I can't validate/end my selection...
This happens both on emulator and real device.

Deployment target : 9.0
iOS version : 11+
Xcode version : 9.2

![simulator screen shot - iphone 8 plus - 2018-02-10 at 13 20 10](https://user-images.githubusercontent.com/3657627/36062068-316f75a0-0e65-11e8-9add-9d0526903ffd.png)

**Comment by hackiftekhar** [comment]
Hey @syc-pad I tried to reproduce this issue but I'm not able to reproduce this. Do you have some specific settings or something else which might cause this issue.
