### ISSUE TITLE
PHPhoto Library Support

### ISSUE THREAD

**Issue by geogerar** [hackiftekhar/IQMediaPickerController#26]
Hi,
thanks for the fantastic tool you gave us....
really a very very nice work.I propose one thing only,
if you can add support for the new PHPhoto library this will be a fantastic enhancement!!

Any way,
I thank you again

George Gerardis

**Comment by hackiftekhar** [comment]
It's in nmy plan but don't have enough time now to do so, but you'll surely see PHPhoto Library support in near future.

**Comment by gupta163** [comment]
is it support (Access) icloud images

**Comment by hackiftekhar** [comment]
PHLibrary support released with v2.0.0, however there are some changes you might need to look and adopt. Currently I don't have much time to write migration documentation.

@gupta163 it's currently isn't optimized for iCloud images.
