### ISSUE TITLE
Add cocoa pods

### ISSUE THREAD

**Issue by Samback** [hackiftekhar/IQMediaPickerController#3]

**Comment by markst** [comment]
@Samback it does seem to be on cocoapods specs:
http://cocoapods.org/?q=IQMediaPickerController

**Comment by markst** [comment]
though the assets don't play very nicely. they need to be placed in a resource directory or something.

**Comment by GABHISEKBUNTY** [comment]
@Samback @markst  So which library are you both suggesting for this

**Comment by hackiftekhar** [comment]
@markst you are correct, I need to add it to a resource directory to work with CocoaPods.

**Comment by smn-khan** [comment]
pods using some other repo.. i am using pod as mentioned .. but it asys .. "Repo not found"

**Comment by smn-khan** [comment]
https://www.dropbox.com/s/nowmlrg2vh8d7a4/Screenshot%202017-10-20%2015.19.16.png?dl=0
Screen shot
