### ISSUE TITLE
Subclassable. 

### ISSUE THREAD

**Issue by markst** [hackiftekhar/IQMediaPickerController#6]
I'm subclassing `IQMediaCaptureController` & building my own view layout from a xib. This means overriding `loadView` & not calling super. 

`IQMediaCaptureController` isn't very nicely subclass-able. I wonder if this can be improved?
For example here what I'm exposing:

``` objc
@interface IQMediaCaptureController () <IQMediaViewDelegate,IQCaptureSessionDelegate,IQAssetsPickerControllerDelegate>
@property (nonatomic,weak) IBOutlet IQMediaView * mediaView;
- (IQCaptureSession *)session;
- (void)updateDuration;
- (void)updateUI;
- (void)setCaptureDevice:(IQMediaCaptureControllerCameraDevice)captureDevice animated:(BOOL)animated;
/*
- (NSMutableArray *)videoURLs;
- (NSMutableArray *)arrayImagesAttribute;
*/
- (void)selectAction:(UIButton *)sender;
@end
```

It would be nice if it could subclassed better & allow for the view to be created/customised from a xib.

**Comment by hackiftekhar** [comment]
sorry, but you are correct that it's not very nicely done for providing subclassing facilities. Unfortunately it will be very hard to expose some methods to do override UI elements. It would really be a pain. If you need then you should fork repo and change the code according to requirement.

Just to let you know I've redesigned the whole UI to look it more better. Please have a look.
